version: '2'
services:
  app:
    build: .
    volumes:
     - "./:/simobot"
    links:
     - redis
     - ircdjs
  redis:
    image: "redis:alpine"
  ircdjs:
    build:
      context: .
      dockerfile: Dockerfile_ircdjs
    ports:
     - "6667:6667"
