version: '2'
services:
  app:
    build: .
    links:
     - redis
     - ircdjs
    volumes:
      - "./simojs-data/:/simojs-data"
    links:
      - "virtualsimo:virtualsimo"
  redis:
    build:
      context: .
      dockerfile: Dockerfile_redis
    volumes:
      - "./redis-data/:/redis-data"
    network_mode: "host"
  ircdjs:
    build:
      context: .
      dockerfile: Dockerfile_ircdjs
    ports:
     - "6667:6667"
  virtualsimo:
    build:
      context: './virtual_private_simo/'
    mem_limit: 4000000000
    cpuset: '3'
    cpu_quota: 50000
    entrypoint: 'node index.js'
    
