version: '2'
services:
  app:
    build: .
    links:
     - redis
     - ircdjs
    volumes:
      - "./simojs-data/:/simojs-data"
  redis:
    build:
      context: .
      dockerfile: Dockerfile_redis
    volumes:
      - "./redis-data/:/redis-data"
    network_mode: "host"
  ircdjs:
    build:
      context: .
      dockerfile: Dockerfile_ircdjs
    ports:
     - "6667:6667"
