version: '2'
services:
  pythonsimo:
    build: 
      context: .
      dockerfile: Dockerfile_pythonsimo
    links:
      - redis
    restart: always

  simojs:
    build: .
    links:
     - redis
     - pythonsimo
     - influxdb
    volumes:
      - "./simojs-data/:/simojs-data"
    restart: always
    ports:
     - "8123:8123"
     - "127.0.0.1:9229:9229"

  redis:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_redis
    volumes:
      - "./redis-data/:/redis-data"

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes:
      - "./influxdb_data:/var/lib/influxdb"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - "GF_SERVER_ROOT_URL=http://grafana.prototyping.xyz"
    ports:
      - "127.0.0.1:3000:3000"
    links:
      - influxdb
    volumes:
      - "./grafana_data:/var/lib/grafana"

  telegraf:
    build:
      context: .
      dockerfile: Dockerfile_telegraf
    container_name: telegraf
    links:
      - influxdb
      - redis

# ircdjs:
#   restart: always
#   build:
#     context: .
#     dockerfile: Dockerfile_ircdjs
#   ports:
#    - "6667:6667"
#  virtualsimo:
#    restart: always
#    build:
#      context: './virtual_private_simo/'
#    mem_limit: 4000000000
#    cpuset: '3'
#    cpu_quota: 50000
#    entrypoint: 'node index.js'
#    ports:
#      - "3500:3500"
