version: '2'
services:
  pythonsimo:
    build: 
      context: .
      dockerfile: Dockerfile_pythonsimo
    links:
      - redis
    restart: always

  simojs:
    build: .
    links:
     - redis
     - pythonsimo
    volumes:
      - "./simojs-data/:/simojs-data"
    restart: always
    ports:
     - "8123:8123"

  redis:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_redis
    volumes:
      - "./redis-data/:/redis-data"

#  ircdjs:
#    restart: always
#    build:
#      context: .
#      dockerfile: Dockerfile_ircdjs
#    ports:
#     - "6667:6667"
#  virtualsimo:
#    restart: always
#    build:
#      context: './virtual_private_simo/'
#    mem_limit: 4000000000
#    cpuset: '3'
#    cpu_quota: 50000
#    entrypoint: 'node index.js'
#    ports:
#      - "3500:3500"
